### ISSUE TITLE
Studio Config like TV Networks?

### ISSUE THREAD

**Issue by TSPARR** [TheChrisK/PMM#8]
This is great! I've implemented the TV Networks and Status overlays and it looks super clean. Love it! I noticed you had the top-left corner images for studios in this repo, but there isn't a corresponding config file that I've noticed. Would you be able to provide some guidance on implementing that?

**Comment by TheChrisK** [comment]
I haven't implemented that yet, but I did import the images from [@s0len](https://github.com/s0len/meta-manager-config?tab=readme-ov-file#studio-overlay-in-ribbon-style-in-the-top-left-corner). You can use his config or mine, it's up to you. I don't plan on removing the images from my repo. I may end up using it down the road.

```yaml
- pmm: studio
      template_variables:
            horizontal_align: left
            horizontal_offset: 0
            vertical_align: top
            vertical_offset: 0
            back_width: 1000
            back_height: 1500
            url: https://raw.githubusercontent.com/TheChrisK/PMM/main/overlays/studio-top-left/<<key>>.png
            back_color: 00
```
